#!/bin/bash

# GitHub部署密钥设置脚本
# 用于将服务器SSH公钥添加到GitHub仓库

echo "🔑 GitHub部署密钥设置脚本"
echo "================================"
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1. 复制以下服务器公钥："
echo "----------------------------------------"
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRS1KQ0FGDY7H9LO2lmONKzaWqbVtOU38cMo9cixA1REpyWj7iFTGCHZs7/hw+ylnc2S/raQkC/SoH4LJHIwEzACMSU8OmYGJnhiIM33vPoXP5Wpl2+6IOVkFoNsaYaezcyhrkKzKUXShLHCKa6Io/FYxv2iMQNI67oTcz/5g7YGUrlGrF3iRElE24FrTMgm3rJSMT/fAxqGKbQOXedf1Meyc067ff+LCIN0ew4NinGv0JxfWkINLmDWK7GH/CEJ6D5/brHkG41IJLvVbgU7b0UpMTnlMDf+wkXJuV9MixWw5eFKvTgBxSQfBSCF0WbX3prhzBbUW7HQ5CCLSrsv2brEadeg8JuEbF2qw/9YhFiYuAimoo1Pzx7CLmSLBE5f+R84n6OznWZsdK5BTNh0Fz0Cj2NhVd5uQXMT7pxPR92w5Krtbl8GaZbxo0sPBRE97DsJqk5h1BJVQdHNR7D8CyjA1c7r/wqEhWe0EXc2kBgAy6395yP9RAmm/ezME9+zAbx6xPsrOldLMxntD+iahwKo82db/UlDeCsZbTvG9Z0+XSPnhPTiQX0CoygqG3sDFTMo7oLV75fJE5vpwMble3Mr8+6dnoy3s7o3sqxe8B9OZcRLVtCpfYbBcemXunUYajLrjsPG+sfJRov9x7Xyy1KArZ5n5XaJmABe9YdrjzGw== server@jesse-trading"
echo "----------------------------------------"
echo ""
echo "2. 访问GitHub仓库设置页面："
echo "   https://github.com/ronalzhang/jesse/settings/keys"
echo ""
echo "3. 点击 'Add deploy key' 按钮"
echo ""
echo "4. 填写以下信息："
echo "   - Title: Jesse+ Server Deploy Key"
echo "   - Key: 粘贴上面的公钥"
echo "   - 勾选 'Allow write access'"
echo ""
echo "5. 点击 'Add key' 保存"
echo ""
echo "6. 完成后运行以下命令测试连接："
echo "   sshpass -p 'Pr971V3j' ssh root@156.236.74.200 'ssh -T git@github.com'"
echo ""
echo "7. 如果看到 'Hi ronalzhang! You've successfully authenticated...' 说明配置成功"
echo ""
echo "8. 然后运行以下命令拉取代码："
echo "   sshpass -p 'Pr971V3j' ssh root@156.236.74.200 'cd /root/Jesse+ && git pull origin main'"
echo ""
echo "✅ 设置完成后，就可以使用 deploy_server.sh 脚本进行自动部署了！" 